### ISSUE TITLE
rule download_names_and_taxonpath now working

### ISSUE THREAD

**Issue by yeonbumkim** [attayeb/snaq#4]
Dear author,
Hi, I've tried to run DEMO RUN but there's something wrong.
The rule "download_names_and_taxonpath" not working.
So, I tried to download manually on https://github.com/attayeb/snaq/releases/download/testing/names.json and https://github.com/attayeb/snaq/releases/download/testing/taxonpath.json. 
There are empy locations. Would you please check the files? Thanks.

Error in rule download_names_and_taxonpath:
    jobid: 27
    output: db/taxonpath.json, db/names.json
    shell:
        
          cd db 
          wget https://github.com/attayeb/snaq/releases/download/testing/names.json
          wget https://github.com/attayeb/snaq/releases/download/testing/taxonpath.json
          
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by attayeb** [comment]
Dear [yeonbumkim](https://github.com/yeonbumkim)
Thank you for bringing the issue of missing files to our attention. We appreciate your feedback and have taken the necessary steps to address the problem. We believe that the issue has been resolved and would kindly request you to try it again and let us know the outcome.

If you continue to experience any issues or have any further concerns, please do not hesitate to reach out to us. We are always ready to help.

Best regards,
